const { generateWAMessageFromContent, proto } = (await import('@whiskeysockets/baileys')).default

var handler = async (m, { conn, text }) => {

  conn.reply(m.chat, `☽ Buscando un piropo con Shadow Garden, espera un momento...`, m)

  conn.reply(
    `*┏━━━━━━━━━━━━━━━━━━━━━━┓*
❥ "${pickRandom(global.piropo)}" ✦
*┗━━━━━━━━━━━━━━━━━━━━━━┛*`
    m
  )

}

handler.help = ['piropo']
handler.tags = ['fun']
handler.command = ['piropo']
handler.fail = null
handler.exp = 0
handler.group = true
handler.register = true

export default handler

let hasil = Math.floor(Math.random() * 5000)
function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

global.piropo = [
  "Si tu sonrisa fuera un delito, ya estaría cumpliendo cadena perpetua.",
  "Eres la razón por la que el día mejora sin esfuerzo.",
  "Tienes algo que hace que todo se vea mejor.",
  "Tu mirada debería venir con advertencia de peligro.",
  "Eres como un buen recuerdo: imposible de olvidar.",
  "Si la belleza fuera tiempo, tú serías la eternidad.",
  "Tienes el tipo de luz que no se apaga nunca.",
  "Tu presencia hace que todo sea más bonito.",
  "Eres de esas personas que dejan huella sin tocar.",
  "No sé si eres real o un buen sueño.",
  "Tu forma de ser es lo que más atrae.",
  "Eres como un día perfecto sin nubes.",
  "Contigo hasta lo simple se siente especial.",
  "Tienes algo que no se puede explicar, solo sentir.",
  "Tu energía cambia cualquier ambiente.",
  "Eres la calma en medio del ruido.",
  "Si sonreír fuera arte, tú serías museo.",
  "Eres más bonita que cualquier paisaje.",
  "Tu voz debería ser música.",
  "Eres el detalle que hace falta en todo.",
  "Tienes algo que hace que todos miren.",
  "Eres como un buen momento congelado en el tiempo.",
  "Tu forma de existir alegra sin esfuerzo.",
  "Eres imposible de ignorar.",
  "Tienes la magia de mejorar cualquier día.",
  "Eres la definición de algo bonito sin explicación.",
  "Tu presencia se siente aunque no hables.",
  "Eres un pensamiento bonito constante.",
  "Tienes una forma de ser que enamora sin querer.",
  "Eres como un rayo de sol inesperado.",
  "Todo contigo se siente más ligero.",
  "Eres la razón de una sonrisa sin motivo.",
  "Tienes algo que simplemente destaca.",
  "Eres de esas personas que no se reemplazan.",
  "Tu esencia es lo que te hace única.",
  "Eres como un descanso para la mente.",
  "Tienes una belleza que no depende de nada.",
  "Eres lo bonito en medio de lo común.",
  "Tu forma de ser es tu mejor encanto.",
  "Eres como un buen día que no quieres que termine.",
  "Tienes algo que hace que todo valga la pena.",
  "Eres la definición de tranquilidad bonita.",
  "Tu presencia se siente como paz.",
  "Eres más interesante que cualquier historia.",
  "Tienes algo que simplemente atrae.",
  "Eres como una sonrisa inesperada.",
  "Todo contigo se siente más suave.",
  "Eres lo que hace especial un momento cualquiera.",
  "Tienes algo que no se olvida.",
  "Eres como una luz en lo cotidiano.",
  "Tu forma de ser destaca sin esfuerzo.",
  "Eres un motivo para sonreír.",
  "Tienes una vibra que gusta.",
  "Eres como un pensamiento bonito repentino.",
  "Todo en ti se siente natural y bonito.",
  "Eres la calma que se nota.",
  "Tienes algo que hace que mirarte sea fácil.",
  "Eres como un recuerdo feliz.",
  "Tu presencia hace todo más amable.",
  "Eres de esas personas que suman.",
  "Tienes algo que mejora cualquier lugar.",
  "Eres como una pausa agradable.",
  "Todo contigo se siente mejor.",
  "Eres un detalle perfecto sin esfuerzo.",
  "Tienes algo que llama la atención sin intentar.",
  "Eres como un día sin problemas.",
  "Tu forma de ser es lo que más gusta.",
  "Eres la razón de un buen pensamiento.",
  "Tienes algo que hace que te recuerden.",
  "Eres como un momento tranquilo.",
  "Todo en ti es naturalmente bonito.",
  "Eres la definición de algo agradable.",
  "Tienes una forma de ser que destaca sola.",
  "Eres como una sonrisa sincera.",
  "Tu presencia ilumina sin querer.",
  "Eres un pensamiento bonito constante.",
  "Tienes algo que hace bien.",
  "Eres como un día perfecto simple.",
  "Todo contigo se siente correcto.",
  "Eres la calma en el caos.",
  "Tienes algo que gusta sin explicación.",
  "Eres como un buen instante.",
  "Tu forma de ser es suficiente.",
  "Eres de esas personas que hacen bien.",
  "Tienes algo que hace sonreír.",
  "Eres como un momento bonito inesperado.",
  "Todo en ti se siente natural.",
  "Eres la razón de algo bueno.",
  "Tienes una presencia agradable.",
  "Eres como un descanso mental.",
  "Tu forma de ser suma siempre.",
  "Eres algo que alegra el día.",
  "Tienes algo que no se busca, se encuentra.",
  "Eres como un detalle bonito.",
  "Todo contigo fluye mejor.",
  "Eres la definición de algo agradable.",
  "Tienes algo que no se explica.",
  "Eres como una luz suave.",
  "Tu presencia es suficiente.",
  "Eres de esas personas que gustan.",
  "Tienes algo que hace bien al alma.",
  "Eres como un momento perfecto simple.",
  "Todo en ti es armonioso.",
  "Eres la calma bonita.",
  "Tienes algo que se siente bien.",
  "Eres como un buen instante repetido.",
  "Tu forma de ser es especial.",
  "Eres algo que alegra sin esfuerzo.",
  "Tienes una energía bonita.",
  "Eres como un pensamiento lindo.",
  "Todo contigo es mejor.",
  "Eres la paz en forma de persona.",
  "Tienes algo que encanta.",
  "Eres como un día bonito.",
  "Tu presencia es agradable.",
  "Eres de esas personas que brillan.",
  "Tienes algo que gusta naturalmente.",
  "Eres como una sonrisa leve.",
  "Todo en ti es bonito.",
  "Eres la razón de algo bueno.",
  "Tienes algo que destaca.",
  "Eres como un momento tranquilo bonito.",
  "Tu forma de ser es perfecta así.",
  "Eres algo que suma siempre.",
  "Tienes una forma de ser especial.",
  "Eres como un recuerdo bonito.",
  "Todo contigo es más simple.",
  "Eres la calma en todo.",
  "Tienes algo que atrae sin razón.",
  "Eres como un instante feliz.",
  "Tu presencia es agradable siempre.",
  "Eres de esas personas que gustan sin esfuerzo.",
  "Tienes algo que hace bien.",
  "Eres como un buen pensamiento.",
  "Todo en ti fluye bien.",
  "Eres la definición de bonito simple.",
  "Tienes algo que no pasa desapercibido.",
  "Eres como una luz suave constante.",
  "Tu forma de ser es bonita.",
  "Eres algo que alegra sin querer.",
  "Tienes una vibra tranquila.",
  "Eres como un día sin ruido.",
  "Todo contigo es mejor.",
  "Eres la calma que gusta.",
  "Tienes algo que mejora todo.",
  "Eres como un momento bonito simple.",
  "Tu presencia es suficiente.",
  "Eres de esas personas que brillan sin intentar.",
  "Tienes algo que gusta mucho.",
  "Eres como un pensamiento bonito.",
  "Todo en ti es agradable.",
  "Eres la razón de algo bueno.",
  "Tienes algo que destaca.",
  "Eres como un instante tranquilo.",
  "Tu forma de ser es bonita.",
  "Eres algo que alegra.",
  "Tienes una energía bonita.",
  "Eres como un día suave.",
  "Todo contigo es armonioso.",
  "Eres la paz bonita.",
  "Tienes algo que se siente bien.",
  "Eres como un recuerdo agradable.",
  "Tu presencia suma.",
  "Eres de esas personas que gustan.",
  "Tienes algo que encanta.",
  "Eres como un momento feliz.",
  "Todo en ti es simple y bonito.",
  "Eres la calma que gusta.",
  "Tienes algo que mejora el día.",
  "Eres como un pensamiento suave.",
  "Tu forma de ser es especial.",
  "Eres algo que alegra siempre.",
  "Tienes una vibra bonita.",
  "Eres como un instante perfecto.",
  "Todo contigo es mejor.",
  "Eres la definición de algo agradable.",
  "Tienes algo que gusta naturalmente.",
  "Eres como una sonrisa tranquila.",
  "Tu presencia es bonita.",
  "Eres de esas personas que iluminan.",
  "Tienes algo que hace bien.",
  "Eres como un día bonito simple.",
  "Todo en ti fluye bien.",
  "Eres la calma constante.",
  "Tienes algo que se siente bonito.",
  "Eres como un momento suave.",
  "Tu forma de ser es agradable.",
  "Eres algo que gusta sin razón.",
  "Tienes una energía especial.",
  "Eres como un pensamiento lindo.",
  "Todo contigo es armonía.",
  "Eres la razón de algo bueno.",
  "Tienes algo que destaca.",
  "Eres como un instante bonito.",
  "Tu presencia es suficiente.",
  "Eres de esas personas que suman.",
  "Tienes algo que alegra.",
  "Eres como un recuerdo feliz.",
  "Todo en ti es agradable.",
  "Eres la calma bonita constante."
]